
server:
  port: 8090

spring:
  datasource:
    #数据库链接URL
    #jdbc:mysql://localhost:3306/数据库名?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/wms_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
    #MySQL 8.x 驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

Logging:
  level:
    com.wms: debug